=== mrbalazs5/db_msc_ea/beadando2_XML/autok.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="kereskedes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="auto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipus" type="xs:string"/>
                            <xs:element name="sebesseg" type="xs:positiveInteger"/>
                            <xs:element name="evjarat" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="rendszam" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mrbalazs5/db_msc_ea/beadando2_XML/autok.xml
<?xml version="1.0" encoding="UTF-8"?>

<kereskedes 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="autok.xsd"
>
	<auto rendszam="ABC-123">
		<tipus>Ford</tipus>
		<sebesseg>200</sebesseg>
		<evjarat>2012</evjarat>
	</auto>
	<auto rendszam="BCD-456">
		<tipus>Audi</tipus>
		<sebesseg>250</sebesseg>
		<evjarat>2015</evjarat>
	</auto>
	<auto rendszam="EFG-789">
		<tipus>Mercedes</tipus>
		<sebesseg>170</sebesseg>
		<evjarat>1995</evjarat>
	</auto>
</kereskedes>
